# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_update_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61gent_update_messages.proto\x12\x11\x61xon.agent_update\"\x81\x01\n\x12\x41gentUpdateCommand\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x16\n\x0etarget_version\x18\x02 \x01(\t\x12\x11\n\tindex_url\x18\x03 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\r\x12\x0f\n\x07\x64ry_run\x18\x05 \x01(\x08\"\xef\x03\n\x13\x41gentUpdateResponse\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12=\n\x06status\x18\x02 \x01(\x0e\x32-.axon.agent_update.AgentUpdateResponse.Status\x12\x18\n\x10previous_version\x18\x03 \x01(\t\x12\x17\n\x0f\x63urrent_version\x18\x04 \x01(\t\x12\x1b\n\x13previous_ce_version\x18\x05 \x01(\t\x12\x1a\n\x12\x63urrent_ce_version\x18\x06 \x01(\t\x12\x1f\n\x17previous_shared_version\x18\x07 \x01(\t\x12\x1e\n\x16\x63urrent_shared_version\x18\x08 \x01(\t\x12\x17\n\x0f\x63ompleted_steps\x18\t \x03(\t\x12\x14\n\x0c\x66\x61iled_steps\x18\n \x03(\t\x12\x15\n\rerror_message\x18\x0b \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x0c \x01(\x04\"y\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x16\n\x12STATUS_ROLLED_BACK\x10\x02\x12\x11\n\rSTATUS_FAILED\x10\x03\x12\x1d\n\x19STATUS_ALREADY_AT_VERSION\x10\x04\"-\n\x13\x41gentVersionRequest\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\"\xd5\x01\n\x14\x41gentVersionResponse\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x12\n\nee_version\x18\x02 \x01(\t\x12\x12\n\nce_version\x18\x03 \x01(\t\x12\x16\n\x0eshared_version\x18\x04 \x01(\t\x12\x19\n\x11installer_version\x18\x05 \x01(\t\x12\x18\n\x10running_services\x18\x06 \x03(\t\x12\x1a\n\x12update_in_progress\x18\x07 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x08 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_update_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AGENTUPDATECOMMAND']._serialized_start=51
  _globals['_AGENTUPDATECOMMAND']._serialized_end=180
  _globals['_AGENTUPDATERESPONSE']._serialized_start=183
  _globals['_AGENTUPDATERESPONSE']._serialized_end=678
  _globals['_AGENTUPDATERESPONSE_STATUS']._serialized_start=557
  _globals['_AGENTUPDATERESPONSE_STATUS']._serialized_end=678
  _globals['_AGENTVERSIONREQUEST']._serialized_start=680
  _globals['_AGENTVERSIONREQUEST']._serialized_end=725
  _globals['_AGENTVERSIONRESPONSE']._serialized_start=728
  _globals['_AGENTVERSIONRESPONSE']._serialized_end=941
# @@protoc_insertion_point(module_scope)
