# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_messages.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62ridge_messages.proto\x12\x08\x61xon.ovs\"\xc7\x01\n\rBridgeCommand\x12&\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x16.axon.ovs.BridgeAction\x12\x13\n\x0b\x62ridge_name\x18\x02 \x01(\t\x12\r\n\x05ports\x18\x03 \x03(\t\x12\x18\n\x10openflow_version\x18\x04 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\x12\x11\n\tdevice_id\x18\x06 \x01(\t\x12\x0f\n\x07site_id\x18\x07 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x08 \x01(\x04\"\xe6\x01\n\x0e\x42ridgeResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.axon.ovs.BridgeResponseStatus\x12\x13\n\x0b\x62ridge_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12&\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x16.axon.ovs.BridgeAction\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\x12\x14\n\x0c\x61\x63tive_ports\x18\x06 \x03(\t\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x04\x12\x12\n\nerror_code\x18\x08 \x01(\t*\x81\x01\n\x0c\x42ridgeAction\x12\x1d\n\x19\x42RIDGE_ACTION_UNSPECIFIED\x10\x00\x12\x18\n\x14\x42RIDGE_ACTION_CREATE\x10\x01\x12\x18\n\x14\x42RIDGE_ACTION_DELETE\x10\x02\x12\x1e\n\x1a\x42RIDGE_ACTION_UPDATE_PORTS\x10\x03*\xd5\x01\n\x14\x42ridgeResponseStatus\x12&\n\"BRIDGE_RESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\"\n\x1e\x42RIDGE_RESPONSE_STATUS_SUCCESS\x10\x01\x12 \n\x1c\x42RIDGE_RESPONSE_STATUS_ERROR\x10\x02\x12)\n%BRIDGE_RESPONSE_STATUS_ALREADY_EXISTS\x10\x03\x12$\n BRIDGE_RESPONSE_STATUS_NOT_FOUND\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BRIDGEACTION']._serialized_start=471
  _globals['_BRIDGEACTION']._serialized_end=600
  _globals['_BRIDGERESPONSESTATUS']._serialized_start=603
  _globals['_BRIDGERESPONSESTATUS']._serialized_end=816
  _globals['_BRIDGECOMMAND']._serialized_start=36
  _globals['_BRIDGECOMMAND']._serialized_end=235
  _globals['_BRIDGERESPONSE']._serialized_start=238
  _globals['_BRIDGERESPONSE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
