# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier_flow_stats_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$classifier_flow_stats_messages.proto\x12\x0f\x61xon.classifier\"\x99\x03\n\x18\x43lassifierFlowStatsEntry\x12\x17\n\x0fopenflow_cookie\x18\x01 \x01(\x04\x12\x19\n\x11\x63lassification_id\x18\x02 \x01(\r\x12\x11\n\tflow_hash\x18\x03 \x01(\r\x12\x10\n\x08\x61pp_name\x18\x04 \x01(\t\x12\x12\n\nbyte_count\x18\x05 \x01(\x04\x12\x14\n\x0cpacket_count\x18\x06 \x01(\x04\x12\x14\n\x0c\x64uration_sec\x18\x07 \x01(\x02\x12\x13\n\x0b\x61\x63tion_type\x18\x08 \x01(\t\x12\x10\n\x08meter_id\x18\t \x01(\r\x12\x10\n\x08priority\x18\n \x01(\r\x12\x10\n\x08protocol\x18\x0b \x01(\t\x12\x0f\n\x07src_mac\x18\x0c \x01(\t\x12\x0f\n\x07\x64st_mac\x18\r \x01(\t\x12\x0e\n\x06src_ip\x18\x0e \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x0f \x01(\t\x12\x10\n\x08src_port\x18\x10 \x01(\r\x12\x10\n\x08\x64st_port\x18\x11 \x01(\r\x12\x14\n\x0csrc_hostname\x18\x12 \x01(\t\x12\x1d\n\x15requested_server_name\x18\x13 \x01(\t\"\xbe\x01\n\x18\x43lassifierFlowStatsBatch\x12\x0f\n\x07site_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x13\n\x0b\x62ridge_name\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x04\x12\x38\n\x05stats\x18\x05 \x03(\x0b\x32).axon.classifier.ClassifierFlowStatsEntry\x12\x19\n\x11poll_interval_sec\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_flow_stats_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLASSIFIERFLOWSTATSENTRY']._serialized_start=58
  _globals['_CLASSIFIERFLOWSTATSENTRY']._serialized_end=467
  _globals['_CLASSIFIERFLOWSTATSBATCH']._serialized_start=470
  _globals['_CLASSIFIERFLOWSTATSBATCH']._serialized_end=660
# @@protoc_insertion_point(module_scope)
