# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier_messages.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63lassifier_messages.proto\x12\x0f\x61xon.classifier\"\xa0\x05\n\x0e\x43lassifiedFlow\x12\x0e\n\x06src_ip\x18\x01 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\t\x12\x10\n\x08src_port\x18\x03 \x01(\r\x12\x10\n\x08\x64st_port\x18\x04 \x01(\r\x12\x0f\n\x07src_mac\x18\x05 \x01(\t\x12\x0f\n\x07\x64st_mac\x18\x06 \x01(\t\x12\x0e\n\x06is_tcp\x18\x07 \x01(\x08\x12\x16\n\x0epayload_sample\x18\x08 \x01(\x0c\x12\x0f\n\x07\x66low_id\x18\t \x01(\r\x12\x18\n\x10\x61pplication_name\x18\n \x01(\t\x12\x1c\n\x14\x61pplication_category\x18\x0b \x01(\t\x12\x1e\n\x16\x61pplication_confidence\x18\x0c \x01(\r\x12\x1d\n\x15requested_server_name\x18\r \x01(\t\x12\x1a\n\x12\x63lient_fingerprint\x18\x0e \x01(\t\x12\x1a\n\x12server_fingerprint\x18\x0f \x01(\t\x12\x1d\n\x15\x62idirectional_packets\x18\x10 \x01(\r\x12\x1b\n\x13\x62idirectional_bytes\x18\x11 \x01(\x04\x12!\n\x19\x62idirectional_duration_ms\x18\x12 \x01(\r\x12\x17\n\x0fsrc2dst_packets\x18\x13 \x01(\r\x12\x17\n\x0f\x64st2src_packets\x18\x14 \x01(\r\x12\x15\n\rsrc2dst_bytes\x18\x15 \x01(\x04\x12\x15\n\rdst2src_bytes\x18\x16 \x01(\x04\x12\x12\n\nsni_source\x18\x17 \x01(\t\x12\x1c\n\x14payload_packet_count\x18\x18 \x01(\r\x12\x17\n\x0fopenflow_cookie\x18\x19 \x01(\x04\x12\x19\n\x11\x63lassification_id\x18\x1a \x01(\r\x12\x1b\n\x13normalized_app_name\x18\x1b \x01(\t\"\xae\x01\n\x13\x43lassifiedFlowBatch\x12\x11\n\tswitch_id\x18\x01 \x01(\t\x12\x0f\n\x07site_id\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x04\x12.\n\x05\x66lows\x18\x05 \x03(\x0b\x32\x1f.axon.classifier.ClassifiedFlow\x12\x1a\n\x12\x63lassifier_version\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLASSIFIEDFLOW']._serialized_start=47
  _globals['_CLASSIFIEDFLOW']._serialized_end=719
  _globals['_CLASSIFIEDFLOWBATCH']._serialized_start=722
  _globals['_CLASSIFIEDFLOWBATCH']._serialized_end=896
# @@protoc_insertion_point(module_scope)
