# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_lifecycle_messages.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64\x65vice_lifecycle_messages.proto\x12\x15\x61xon.device_lifecycle\"\x96\x01\n\x16\x44\x65viceUninstallCommand\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x16\n\x0eremove_bridges\x18\x02 \x01(\x08\x12\x1a\n\x12remove_credentials\x18\x03 \x01(\x08\x12\x19\n\x11remove_agent_code\x18\x04 \x01(\x08\x12\x15\n\rgrace_seconds\x18\x05 \x01(\r\"\x96\x02\n\x17\x44\x65viceUninstallResponse\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x45\n\x06status\x18\x02 \x01(\x0e\x32\x35.axon.device_lifecycle.DeviceUninstallResponse.Status\x12\x17\n\x0f\x63ompleted_steps\x18\x03 \x03(\t\x12\x14\n\x0c\x66\x61iled_steps\x18\x04 \x03(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"V\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x12\n\x0eSTATUS_PARTIAL\x10\x02\x12\x11\n\rSTATUS_FAILED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_lifecycle_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEVICEUNINSTALLCOMMAND']._serialized_start=59
  _globals['_DEVICEUNINSTALLCOMMAND']._serialized_end=209
  _globals['_DEVICEUNINSTALLRESPONSE']._serialized_start=212
  _globals['_DEVICEUNINSTALLRESPONSE']._serialized_end=490
  _globals['_DEVICEUNINSTALLRESPONSE_STATUS']._serialized_start=404
  _globals['_DEVICEUNINSTALLRESPONSE_STATUS']._serialized_end=490
# @@protoc_insertion_point(module_scope)
