# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ee_data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65\x65_data_service.proto\x12\taxon.data\"/\n\tRawPacket\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x04\"\x90\x03\n\x06\x45\x45\x46low\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\x0e\n\x06src_ip\x18\x02 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x03 \x01(\t\x12\x10\n\x08src_port\x18\x04 \x01(\r\x12\x10\n\x08\x64st_port\x18\x05 \x01(\r\x12\x0f\n\x07src_mac\x18\x06 \x01(\t\x12\x0f\n\x07\x64st_mac\x18\x07 \x01(\t\x12\x0e\n\x06is_tcp\x18\x08 \x01(\x08\x12\x18\n\x10\x61pplication_name\x18\t \x01(\t\x12\x1d\n\x15requested_server_name\x18\n \x01(\t\x12\x1d\n\x15\x62idirectional_packets\x18\x0b \x01(\x04\x12\x1b\n\x13\x62idirectional_bytes\x18\x0c \x01(\x04\x12\x18\n\x10\x66low_duration_ms\x18\r \x01(\x04\x12)\n\x0braw_packets\x18\x0e \x03(\x0b\x32\x14.axon.data.RawPacket\x12\x10\n\x08ml_label\x18\x0f \x01(\t\x12\x15\n\rml_confidence\x18\x10 \x01(\x02\x12\x17\n\x0fndpi_confidence\x18\x11 \x01(\x02\"\xe7\x01\n\x0b\x45\x45\x46lowBatch\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07site_id\x18\x02 \x01(\t\x12\x11\n\tswitch_id\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x04\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x06 \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\x01\x12\x11\n\tlongitude\x18\x08 \x01(\x01\x12\x18\n\x10\x63ompressed_flows\x18\t \x01(\x0c\x12\x12\n\nflow_count\x18\n \x01(\r\x12\x12\n\nauth_token\x18\x0b \x01(\t\"+\n\x07\x45\x45\x46lows\x12 \n\x05\x66lows\x18\x01 \x03(\x0b\x32\x11.axon.data.EEFlow\"P\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0e\x66lows_accepted\x18\x02 \x01(\r\x12\x15\n\rerror_message\x18\x03 \x01(\t2U\n\x0f\x46lowDataService\x12\x42\n\x0bIngestFlows\x12\x16.axon.data.EEFlowBatch\x1a\x19.axon.data.IngestResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ee_data_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RAWPACKET']._serialized_start=36
  _globals['_RAWPACKET']._serialized_end=83
  _globals['_EEFLOW']._serialized_start=86
  _globals['_EEFLOW']._serialized_end=486
  _globals['_EEFLOWBATCH']._serialized_start=489
  _globals['_EEFLOWBATCH']._serialized_end=720
  _globals['_EEFLOWS']._serialized_start=722
  _globals['_EEFLOWS']._serialized_end=765
  _globals['_INGESTRESPONSE']._serialized_start=767
  _globals['_INGESTRESPONSE']._serialized_end=847
  _globals['_FLOWDATASERVICE']._serialized_start=849
  _globals['_FLOWDATASERVICE']._serialized_end=934
# @@protoc_insertion_point(module_scope)
