# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ee_data_service_pb2 as ee__data__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ee_data_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlowDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestFlows = channel.stream_unary(
                '/axon.data.FlowDataService/IngestFlows',
                request_serializer=ee__data__service__pb2.EEFlowBatch.SerializeToString,
                response_deserializer=ee__data__service__pb2.IngestResponse.FromString,
                _registered_method=True)


class FlowDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestFlows(self, request_iterator, context):
        """Client-streaming: agent sends batches, collector acknowledges
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestFlows': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestFlows,
                    request_deserializer=ee__data__service__pb2.EEFlowBatch.FromString,
                    response_serializer=ee__data__service__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axon.data.FlowDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axon.data.FlowDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlowDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestFlows(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/axon.data.FlowDataService/IngestFlows',
            ee__data__service__pb2.EEFlowBatch.SerializeToString,
            ee__data__service__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
