# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow_stats_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66low_stats_messages.proto\x12\x0e\x61xon.analytics\"\xc6\x01\n\x0e\x46lowStatsEntry\x12\x17\n\x0fopenflow_cookie\x18\x01 \x01(\x04\x12\x10\n\x08meter_id\x18\x02 \x01(\r\x12\x12\n\nbyte_count\x18\x03 \x01(\x04\x12\x14\n\x0cpacket_count\x18\x04 \x01(\x04\x12\x14\n\x0c\x64uration_sec\x18\x05 \x01(\x02\x12\x10\n\x08priority\x18\x06 \x01(\r\x12\x10\n\x08protocol\x18\x07 \x01(\t\x12\x13\n\x0bmac_address\x18\x08 \x01(\t\x12\x10\n\x08hostname\x18\t \x01(\t\"\x8e\x01\n\x0e\x46lowStatsBatch\x12\x0f\n\x07site_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x13\n\x0b\x62ridge_name\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x04\x12-\n\x05stats\x18\x05 \x03(\x0b\x32\x1e.axon.analytics.FlowStatsEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow_stats_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FLOWSTATSENTRY']._serialized_start=46
  _globals['_FLOWSTATSENTRY']._serialized_end=244
  _globals['_FLOWSTATSBATCH']._serialized_start=247
  _globals['_FLOWSTATSBATCH']._serialized_end=389
# @@protoc_insertion_point(module_scope)
