# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health_check_messages.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhealth_check_messages.proto\x12\x08\x61xon.ovs\"\xd6\x01\n\x12HealthCheckRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x0f\n\x07site_id\x18\x04 \x01(\t\x12\x17\n\x0finclude_bridges\x18\x05 \x01(\x08\x12\x16\n\x0einclude_meters\x18\x06 \x01(\x08\x12\x15\n\rinclude_flows\x18\x07 \x01(\x08\x12\x15\n\rinclude_ports\x18\x08 \x01(\x08\x12\x13\n\x0b\x62ridge_name\x18\t \x01(\t\"i\n\x0b\x42ridgeState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x65xists\x18\x02 \x01(\x08\x12\r\n\x05ports\x18\x03 \x03(\t\x12\x18\n\x10openflow_version\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x61tapath_id\x18\x05 \x01(\t\"x\n\nMeterState\x12\x13\n\x0b\x62ridge_name\x18\x01 \x01(\t\x12\x10\n\x08meter_id\x18\x02 \x01(\r\x12\x0c\n\x04rate\x18\x03 \x01(\r\x12\x12\n\nburst_size\x18\x04 \x01(\r\x12\x12\n\nmeter_type\x18\x05 \x01(\t\x12\r\n\x05\x66lags\x18\x06 \x03(\t\"\xbc\x02\n\x13HealthCheckResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.axon.ovs.HealthCheckStatus\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x04\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x0f\n\x07site_id\x18\x05 \x01(\t\x12&\n\x07\x62ridges\x18\x06 \x03(\x0b\x32\x15.axon.ovs.BridgeState\x12$\n\x06meters\x18\x07 \x03(\x0b\x32\x14.axon.ovs.MeterState\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x16\n\x0epartial_errors\x18\t \x03(\t\x12\x15\n\ragent_version\x18\n \x01(\t\x12\x16\n\x0euptime_seconds\x18\x0b \x01(\x04*\x99\x01\n\x11HealthCheckStatus\x12#\n\x1fHEALTH_CHECK_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bHEALTH_CHECK_STATUS_SUCCESS\x10\x01\x12\x1d\n\x19HEALTH_CHECK_STATUS_ERROR\x10\x02\x12\x1f\n\x1bHEALTH_CHECK_STATUS_PARTIAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_check_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHCHECKSTATUS']._serialized_start=807
  _globals['_HEALTHCHECKSTATUS']._serialized_end=960
  _globals['_HEALTHCHECKREQUEST']._serialized_start=42
  _globals['_HEALTHCHECKREQUEST']._serialized_end=256
  _globals['_BRIDGESTATE']._serialized_start=258
  _globals['_BRIDGESTATE']._serialized_end=363
  _globals['_METERSTATE']._serialized_start=365
  _globals['_METERSTATE']._serialized_end=485
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=488
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=804
# @@protoc_insertion_point(module_scope)
