# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface_messages.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18interface_messages.proto\x12\x13\x61xon.network_device\"<\n\x10NetworkInterface\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\r\"\x80\x01\n\x10InterfaceChanges\x12\x34\n\x05\x61\x64\x64\x65\x64\x18\x01 \x03(\x0b\x32%.axon.network_device.NetworkInterface\x12\x36\n\x07removed\x18\x02 \x03(\x0b\x32%.axon.network_device.NetworkInterface\"\xa3\x01\n\x1bInterfaceChangeNotification\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x39\n\ninterfaces\x18\x02 \x03(\x0b\x32%.axon.network_device.NetworkInterface\x12\x36\n\x07\x63hanges\x18\x03 \x01(\x0b\x32%.axon.network_device.InterfaceChangesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NETWORKINTERFACE']._serialized_start=49
  _globals['_NETWORKINTERFACE']._serialized_end=109
  _globals['_INTERFACECHANGES']._serialized_start=112
  _globals['_INTERFACECHANGES']._serialized_end=240
  _globals['_INTERFACECHANGENOTIFICATION']._serialized_start=243
  _globals['_INTERFACECHANGENOTIFICATION']._serialized_end=406
# @@protoc_insertion_point(module_scope)
