# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meter_messages.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14meter_messages.proto\x12\x08\x61xon.ovs\"\xe1\x01\n\x0cMeterCommand\x12%\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x15.axon.ovs.MeterAction\x12\x10\n\x08meter_id\x18\x02 \x01(\r\x12\x13\n\x0b\x62ridge_name\x18\x03 \x01(\t\x12\'\n\nmeter_type\x18\x04 \x01(\x0e\x32\x13.axon.ovs.MeterType\x12\x0c\n\x04rate\x18\x05 \x01(\r\x12\x12\n\nburst_size\x18\x06 \x01(\r\x12\x11\n\tdevice_id\x18\x07 \x01(\t\x12\x0f\n\x07site_id\x18\x08 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\t \x01(\x04\"\xf6\x01\n\rMeterResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.axon.ovs.MeterResponseStatus\x12\x10\n\x08meter_id\x18\x02 \x01(\r\x12\x13\n\x0b\x62ridge_name\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12%\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32\x15.axon.ovs.MeterAction\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x04\x12\x12\n\nerror_code\x18\x07 \x01(\t\x12-\n\x06source\x18\x08 \x01(\x0e\x32\x1d.axon.ovs.MeterResponseSource*X\n\tMeterType\x12\x1a\n\x16METER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fMETER_TYPE_DROP\x10\x01\x12\x1a\n\x16METER_TYPE_DSCP_REMARK\x10\x02*v\n\x0bMeterAction\x12\x1c\n\x18METER_ACTION_UNSPECIFIED\x10\x00\x12\x17\n\x13METER_ACTION_CREATE\x10\x01\x12\x17\n\x13METER_ACTION_DELETE\x10\x02\x12\x17\n\x13METER_ACTION_MODIFY\x10\x03*\xcf\x01\n\x13MeterResponseStatus\x12%\n!METER_RESPONSE_STATUS_UNSPECIFIED\x10\x00\x12!\n\x1dMETER_RESPONSE_STATUS_SUCCESS\x10\x01\x12\x1f\n\x1bMETER_RESPONSE_STATUS_ERROR\x10\x02\x12(\n$METER_RESPONSE_STATUS_ALREADY_EXISTS\x10\x03\x12#\n\x1fMETER_RESPONSE_STATUS_NOT_FOUND\x10\x04*f\n\x13MeterResponseSource\x12$\n METER_RESPONSE_SOURCE_CONTROLLER\x10\x00\x12)\n%METER_RESPONSE_SOURCE_AGENT_SELF_HEAL\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meter_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METERTYPE']._serialized_start=511
  _globals['_METERTYPE']._serialized_end=599
  _globals['_METERACTION']._serialized_start=601
  _globals['_METERACTION']._serialized_end=719
  _globals['_METERRESPONSESTATUS']._serialized_start=722
  _globals['_METERRESPONSESTATUS']._serialized_end=929
  _globals['_METERRESPONSESOURCE']._serialized_start=931
  _globals['_METERRESPONSESOURCE']._serialized_end=1033
  _globals['_METERCOMMAND']._serialized_start=35
  _globals['_METERCOMMAND']._serialized_end=260
  _globals['_METERRESPONSE']._serialized_start=263
  _globals['_METERRESPONSE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
