# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sniffer_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sniffer_messages.proto\x12\x0b\x61xon.plugin\"\x9f\x01\n\x15SnifferInstallCommand\x12\x13\n\x0b\x62ridge_name\x18\x01 \x01(\t\x12\x19\n\x11monitor_interface\x18\x02 \x01(\t\x12\x16\n\x0eport_to_client\x18\x03 \x01(\t\x12\x16\n\x0eport_to_router\x18\x04 \x01(\t\x12\x11\n\tnum_bytes\x18\x05 \x01(\r\x12\x13\n\x0bnum_packets\x18\x06 \x01(\r\"j\n\x16SnifferInstallResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.axon.plugin.InstallStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0b\x62ridge_name\x18\x03 \x01(\t*e\n\rInstallStatus\x12\x1e\n\x1aINSTALL_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16INSTALL_STATUS_SUCCESS\x10\x01\x12\x18\n\x14INSTALL_STATUS_ERROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sniffer_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INSTALLSTATUS']._serialized_start=309
  _globals['_INSTALLSTATUS']._serialized_end=410
  _globals['_SNIFFERINSTALLCOMMAND']._serialized_start=40
  _globals['_SNIFFERINSTALLCOMMAND']._serialized_end=199
  _globals['_SNIFFERINSTALLRESPONSE']._serialized_start=201
  _globals['_SNIFFERINSTALLRESPONSE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
