# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uptime_check_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1buptime_check_messages.proto\x12\x16\x61xon.uptime_monitoring\"e\n\x15\x41gentHeartbeatRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x0f\n\x07site_id\x18\x04 \x01(\t\"\xb3\x01\n\x16\x41gentHeartbeatResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x0f\n\x07site_id\x18\x04 \x01(\t\x12\x34\n\x06status\x18\x05 \x01(\x0e\x32$.axon.uptime_monitoring.UptimeStatus\x12\x15\n\ragent_version\x18\x06 \x01(\t\"\xb7\x01\n\x13\x45ndpointPingRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x0f\n\x07site_id\x18\x04 \x01(\t\x12\x11\n\ttarget_ip\x18\x05 \x01(\t\x12\x17\n\x0ftarget_hostname\x18\x06 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x07 \x01(\r\x12\r\n\x05\x63ount\x18\x08 \x01(\r\"\x8e\x02\n\x14\x45ndpointPingResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x0f\n\x07site_id\x18\x04 \x01(\t\x12\x11\n\ttarget_ip\x18\x05 \x01(\t\x12\x34\n\x06status\x18\x06 \x01(\x0e\x32$.axon.uptime_monitoring.UptimeStatus\x12\x18\n\x10response_time_ms\x18\x07 \x01(\r\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x18\n\x10successful_pings\x18\t \x01(\r\x12\x14\n\x0c\x66\x61iled_pings\x18\n \x01(\r*[\n\x0cUptimeStatus\x12\x1d\n\x19UPTIME_STATUS_UNSPECIFIED\x10\x00\x12\x14\n\x10UPTIME_STATUS_UP\x10\x01\x12\x16\n\x12UPTIME_STATUS_DOWN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uptime_check_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPTIMESTATUS']._serialized_start=799
  _globals['_UPTIMESTATUS']._serialized_end=890
  _globals['_AGENTHEARTBEATREQUEST']._serialized_start=55
  _globals['_AGENTHEARTBEATREQUEST']._serialized_end=156
  _globals['_AGENTHEARTBEATRESPONSE']._serialized_start=159
  _globals['_AGENTHEARTBEATRESPONSE']._serialized_end=338
  _globals['_ENDPOINTPINGREQUEST']._serialized_start=341
  _globals['_ENDPOINTPINGREQUEST']._serialized_end=524
  _globals['_ENDPOINTPINGRESPONSE']._serialized_start=527
  _globals['_ENDPOINTPINGRESPONSE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
